{
 "title": "Nomad Jobs",
 "description": "Nomad Jobs metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datacenter",
    "label": "DC",
    "query": "label_values(nomad_client_uptime, datacenter)"
   },
   {
    "name": "instance",
    "label": "Host",
    "query": "label_values(nomad_client_uptime{datacenter=~\"$datacenter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nomad_client_uptime{instance=~\"$instance\"})",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(nomad_client_allocs_memory_cache) by (exported_job))",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Allocs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nomad_client_allocations_running{datacenter=\"$datacenter\",instance=~\"$instance\"})",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Block/Peding/Restart",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nomad_client_allocations_blocked{datacenter=\"$datacenter\",instance=~\"$instance\"})",
     "legendFormat": "Blocked",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "expr": "sum(nomad_client_allocations_pending{datacenter=\"$datacenter\",instance=~\"$instance\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(nomad_client_allocations_restart{datacenter=\"$datacenter\",instance=~\"$instance\"})",
     "legendFormat": "Restart "
    }
   ]
  },
  {
   "title": "Summary",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "repeat": "host",
   "targets": [
    {
     "expr": "nomad_client_allocations_migrating{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Migrating"
    },
    {
     "expr": "instanceinstancenomad_client_allocations_blocked{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "nomad_client_allocations_pending{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "nomad_client_allocations_running{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "nomad_client_allocations_terminal{datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Terminal"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nomad_client_unallocated_memory{instance=~\"$instance\"})",
     "legendFormat": "Available (Free)",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "expr": "sum(nomad_client_allocated_memory{instance=~\"$instance\"})",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "CPU (MHz)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nomad_client_unallocated_cpu{instance=~\"$instance\"})",
     "legendFormat": "Available (Free)",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "expr": "sum(nomad_client_allocated_cpu{instance=~\"$instance\"})",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "CPU Usage Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 19 },
   "repeat": "host",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_percent{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "CPU Total Ticks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 19 },
   "repeat": "host",
   "yaxes": [
    { "format": "timeticks" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_ticks{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 25 },
   "repeat": "host",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_rss{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Memory Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 25 },
   "repeat": "host",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_cache{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  }
 ]
}